<?php

namespace Kevinpurwito\LaravelMailcoachApi\Tests;

use Kevinpurwito\LaravelMailcoachApi\MailcoachApiServiceProvider;
use Spatie\LaravelData\LaravelDataServiceProvider;

class TestCase extends \Orchestra\Testbench\TestCase
{
    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function getPackageProviders($app): array
    {
        return [
            MailcoachApiServiceProvider::class,
            LaravelDataServiceProvider::class,
        ];
    }

    public function getEnvironmentSetUp($app)
    {
        // New Dotenv
        if (file_exists(dirname(__DIR__) . '/.env')) {
            (\Dotenv\Dotenv::createImmutable(dirname(__DIR__), '.env'))->load();
        }
    }
}
